# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cafecfd1ce75c14dbbe454df2d12de95d53452dd299a5db1221088c144717c8436ad1f4d67dbcb8453da539605593b45cd0eb76d121d47fd22c2173470f2c186

test:
  secret_key_base: a018a58042a442a7da4a4c1b7218d3ea8468cde5cb41c2f3d9f8a8dddc9caa16d338081fece0ec581806c02b03198d62948b1113fda5c43e42d528842129e020

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
